<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'BACKEND_PERMISSIONS_ATTR_CHILDREN' => 'Потомки',
    'BACKEND_PERMISSIONS_ATTR_DATA' => 'Дата',
    'BACKEND_PERMISSIONS_ATTR_DESCRIPTION' => 'Описание',
    'BACKEND_PERMISSIONS_ATTR_NAME' => 'Название',
    'BACKEND_PERMISSIONS_ATTR_RULE_NAME' => 'Правило',
    'BACKEND_PERMISSIONS_CHILDREN_PROMPT' => 'Выберите потомков',
    'BACKEND_PERMISSIONS_CREATE_SUBMIT' => 'Сохранить',
    'BACKEND_PERMISSIONS_CREATE_SUBTITLE' => 'Добавление правила',
    'BACKEND_PERMISSIONS_CREATE_TITLE' => 'Управление доступом',
    'BACKEND_PERMISSIONS_FLASH_FAIL_ADMIN_CREATE' => 'Не удалось сохранить правило. Попробуйте пожалуйста еще раз!',
    'BACKEND_PERMISSIONS_FLASH_FAIL_ADMIN_DELETE' => 'Не удалось удалить правило. Попробуйте пожалуйста еще раз!',
    'BACKEND_PERMISSIONS_FLASH_FAIL_ADMIN_UPDATE' => 'Не удалось обновить правило. Попробуйте пожалуйста еще раз!',
    'BACKEND_PERMISSIONS_INDEX_SUBTITLE' => 'Список правил',
    'BACKEND_PERMISSIONS_INDEX_TITLE' => 'Управление доступом',
    'BACKEND_PERMISSIONS_NOT_FOUND' => 'Ошибка 404 - страница не найдена!',
    'BACKEND_PERMISSIONS_RULE_NAME_PROMPT' => 'Выберите роль',
    'BACKEND_PERMISSIONS_UPDATE_SUBMIT' => 'Обновить',
    'BACKEND_PERMISSIONS_UPDATE_SUBTITLE' => 'Обновление правила',
    'BACKEND_PERMISSIONS_UPDATE_TITLE' => 'Уплавление доступа',
    'BACKEND_ROLES_ATTR_DATA' => 'Дата',
    'BACKEND_ROLES_ATTR_DESCRIPTION' => 'Описание',
    'BACKEND_ROLES_ATTR_NAME' => 'Название',
    'BACKEND_ROLES_ATTR_PERMISSIONS' => 'Потомственные права',
    'BACKEND_ROLES_ATTR_ROLES' => 'Постомственные роли',
    'BACKEND_ROLES_ATTR_RULE_NAME' => 'Правило',
    'BACKEND_ROLES_CREATE_SUBMIT' => 'Сохранить',
    'BACKEND_ROLES_CREATE_SUBTITLE' => 'Добавление роли',
    'BACKEND_ROLES_CREATE_TITLE' => 'Управление доступом',
    'BACKEND_ROLES_FLASH_FAIL_ADMIN_CREATE' => 'Не удалось сохранить роль. Попробуйте пожалуйста еще раз!',
    'BACKEND_ROLES_FLASH_FAIL_ADMIN_DELETE' => 'Не удалось удалить роль. Попробуйте пожалуйста еще раз!',
    'BACKEND_ROLES_FLASH_FAIL_ADMIN_UPDATE' => 'Не удалось обновить роль. Попробуйте пожалуйста еще раз!',
    'BACKEND_ROLES_INDEX_SUBTITLE' => 'Список ролей',
    'BACKEND_ROLES_INDEX_TITLE' => 'Управление дсотупом',
    'BACKEND_ROLES_NOT_FOUND' => 'Ошибка 404 - страница не найдена!',
    'BACKEND_ROLES_PERMISSIONS_PROMPT' => 'Выберите права',
    'BACKEND_ROLES_ROLES_PROMPT' => 'Выберите роли',
    'BACKEND_ROLES_RULE_NAME_PROMPT' => 'Выберите правило',
    'BACKEND_ROLES_UPDATE_SUBMIT' => 'Обновить',
    'BACKEND_ROLES_UPDATE_SUBTITLE' => 'Обновление роли',
    'BACKEND_ROLES_UPDATE_TITLE' => 'Управление доступом',
    'BACKEND_RULES_ATTR_NAME' => 'Название',
    'BACKEND_RULES_ATTR_NAMESPACE' => 'Простраство имен',
    'BACKEND_RULES_CREATE_SUBMIT' => 'Сохранить',
    'BACKEND_RULES_CREATE_SUBTITLE' => 'Создание правила',
    'BACKEND_RULES_CREATE_TITLE' => 'Управление доступом',
    'BACKEND_RULES_FLASH_FAIL_ADMIN_CREATE' => 'Не удалось сохранить правило. Попробуйте пожалуйста еще раз!',
    'BACKEND_RULES_FLASH_FAIL_ADMIN_DELETE' => 'Не удалось удалить правило. Попробуйте пожалуйста еще раз!',
    'BACKEND_RULES_INDEX_SUBTITLE' => 'Список правил',
    'BACKEND_RULES_INDEX_TITLE' => 'Управление дсотупом',
    'BACKEND_RULES_NOT_FOUND' => 'Ошибка 404 - страница не найдена!',
    'ERROR_MSG_INVALID_CHILDREN' => 'Неверный список потомков',
    'ERROR_MSG_INVALID_NAMESPACE' => 'неверное простраство имен',
    'ERROR_MSG_INVALID_PERMISSIONS_CHILDREN' => 'Неверный список потомстенных прав',
    'ERROR_MSG_INVALID_ROLES_CHILDREN' => 'Неверный список потомстенных ролей',
    'ERROR_MSG_INVALID_RULE_NAME' => 'Название роли',
];
