<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'BACKEND_PERMISSIONS_ATTR_RULE_NAME' => 'Regel-Name',
    'BACKEND_ROLES_ATTR_RULE_NAME' => 'Regel-Name',
    'BACKEND_ROLES_CREATE_SUBMIT' => 'Speichern',
    'BACKEND_ROLES_CREATE_SUBTITLE' => 'Rolle anlegen',
    'BACKEND_ROLES_CREATE_TITLE' => 'Zugriffskontrolle',
    'BACKEND_ROLES_FLASH_FAIL_ADMIN_CREATE' => 'Rolle wurde nicht gespeichert. Bitte nochmals versuchen!',
    'BACKEND_ROLES_FLASH_FAIL_ADMIN_DELETE' => 'Rolle wurde nicht gelöscht. Bitte nochmals versuchen!',
    'BACKEND_ROLES_FLASH_FAIL_ADMIN_UPDATE' => 'Rolle wurde nicht geändert. Bitte nochmals versuchen!',
    'BACKEND_ROLES_INDEX_SUBTITLE' => 'Rollenliste',
    'BACKEND_ROLES_INDEX_TITLE' => 'Zugriffskontrolle',
    'BACKEND_ROLES_NOT_FOUND' => 'Error 404 - page not found!',
    'BACKEND_ROLES_PERMISSIONS_PROMPT' => 'Wähle Kind-Berechtigungen',
    'BACKEND_ROLES_ROLES_PROMPT' => 'Wähle Kind-Rollen',
    'BACKEND_ROLES_RULE_NAME_PROMPT' => 'Wähle eine Regel',
    'BACKEND_ROLES_UPDATE_SUBMIT' => 'Ändern',
    'BACKEND_ROLES_UPDATE_SUBTITLE' => 'Rolle ändern',
    'BACKEND_ROLES_UPDATE_TITLE' => 'Zugriffskontrolle',
    'BACKEND_RULES_ATTR_NAME' => 'Name',
    'BACKEND_RULES_ATTR_NAMESPACE' => 'Namespace',
    'BACKEND_RULES_CREATE_SUBMIT' => 'Speichern',
    'BACKEND_RULES_CREATE_SUBTITLE' => 'Regel anlegen',
    'BACKEND_RULES_CREATE_TITLE' => 'Zugriffskontrolle',
    'BACKEND_RULES_FLASH_FAIL_ADMIN_CREATE' => 'Regel wurde nicht gespeichert. Bitte nochmals versuchen!',
    'BACKEND_RULES_FLASH_FAIL_ADMIN_DELETE' => 'Regel wurde nicht gelöscht. Bitte nochmals versuchen!',
    'BACKEND_RULES_INDEX_SUBTITLE' => 'Regel-Liste',
    'BACKEND_RULES_INDEX_TITLE' => 'Zugriffskontrolle',
    'BACKEND_RULES_NOT_FOUND' => 'Error 404 - page not found!',
    'ERROR_MSG_INVALID_CHILDREN' => 'Ungültiges Kindobjekt',
    'ERROR_MSG_INVALID_NAMESPACE' => 'Ungültiger Namespace',
    'ERROR_MSG_INVALID_PERMISSIONS_CHILDREN' => 'Ungültige Kind-Berechtigungen',
    'ERROR_MSG_INVALID_ROLES_CHILDREN' => 'Ungültige Rollen-Berechtigungen',
    'ERROR_MSG_INVALID_RULE_NAME' => 'Ungültiger Regel-Name',
    'BACKEND_PERMISSIONS_ATTR_CHILDREN' => 'Kind-Berechtigungen',
    'BACKEND_PERMISSIONS_ATTR_DATA' => 'Daten',
    'BACKEND_PERMISSIONS_ATTR_DESCRIPTION' => 'Beschreibung',
    'BACKEND_PERMISSIONS_ATTR_NAME' => 'Name',
    'BACKEND_PERMISSIONS_CHILDREN_PROMPT' => 'Wähle Kindobjekt',
    'BACKEND_PERMISSIONS_CREATE_SUBMIT' => 'Speichern',
    'BACKEND_PERMISSIONS_CREATE_SUBTITLE' => 'Berechtigung angelegt',
    'BACKEND_PERMISSIONS_CREATE_TITLE' => 'Zugriffskontrolle',
    'BACKEND_PERMISSIONS_FLASH_FAIL_ADMIN_CREATE' => 'Berechtigung wurde nicht gespeichert. Bitte nochmals versuchen!',
    'BACKEND_PERMISSIONS_FLASH_FAIL_ADMIN_DELETE' => 'Berechtigung wurde nicht gelöscht. Bitte nochmals versuchen!',
    'BACKEND_PERMISSIONS_FLASH_FAIL_ADMIN_UPDATE' => 'Berechtigung wurde nicht geändert. Bitte nochmals versuchen!',
    'BACKEND_PERMISSIONS_INDEX_SUBTITLE' => 'Berechtigungsliste',
    'BACKEND_PERMISSIONS_INDEX_TITLE' => 'Zugriffskontrolle',
    'BACKEND_PERMISSIONS_NOT_FOUND' => 'Error 404 - page not found!',
    'BACKEND_PERMISSIONS_RULE_NAME_PROMPT' => 'Wähle eine Regel',
    'BACKEND_PERMISSIONS_UPDATE_SUBMIT' => 'Ändern',
    'BACKEND_PERMISSIONS_UPDATE_SUBTITLE' => 'Berechtigung ändern',
    'BACKEND_PERMISSIONS_UPDATE_TITLE' => 'Zugriffskontrolle',
    'BACKEND_ROLES_ATTR_DATA' => 'Daten',
    'BACKEND_ROLES_ATTR_DESCRIPTION' => 'Beschreibung',
    'BACKEND_ROLES_ATTR_NAME' => 'Name',
    'BACKEND_ROLES_ATTR_PERMISSIONS' => 'Kind-Berechtigungen',
    'BACKEND_ROLES_ATTR_ROLES' => 'Kind-Rollen',
];
