<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'BACKEND_PERMISSIONS_ATTR_RULE_NAME' => 'Rule name',
    'BACKEND_ROLES_ATTR_RULE_NAME' => 'Rule name',
    'BACKEND_ROLES_CREATE_SUBMIT' => 'Save',
    'BACKEND_ROLES_CREATE_SUBTITLE' => 'Role creating',
    'BACKEND_ROLES_CREATE_TITLE' => 'Access Control',
    'BACKEND_ROLES_FLASH_FAIL_ADMIN_CREATE' => 'Role has not been saved. Please try again!',
    'BACKEND_ROLES_FLASH_FAIL_ADMIN_DELETE' => 'Role has not been deleted. Please try again!',
    'BACKEND_ROLES_FLASH_FAIL_ADMIN_UPDATE' => 'Role has not been updated. Please try again!',
    'BACKEND_ROLES_INDEX_SUBTITLE' => 'Roles list',
    'BACKEND_ROLES_INDEX_TITLE' => 'Access Control',
    'BACKEND_ROLES_NOT_FOUND' => 'Error 404 - page not found!',
    'BACKEND_ROLES_PERMISSIONS_PROMPT' => 'Choose children permissions',
    'BACKEND_ROLES_ROLES_PROMPT' => 'Choose children roles',
    'BACKEND_ROLES_RULE_NAME_PROMPT' => 'Choose a rule',
    'BACKEND_ROLES_UPDATE_SUBMIT' => 'Update',
    'BACKEND_ROLES_UPDATE_SUBTITLE' => 'Role updating',
    'BACKEND_ROLES_UPDATE_TITLE' => 'Access Control',
    'BACKEND_RULES_ATTR_NAME' => 'Name',
    'BACKEND_RULES_ATTR_NAMESPACE' => 'Namespace',
    'BACKEND_RULES_CREATE_SUBMIT' => 'Save',
    'BACKEND_RULES_CREATE_SUBTITLE' => 'Rule creating',
    'BACKEND_RULES_CREATE_TITLE' => 'Access Control',
    'BACKEND_RULES_FLASH_FAIL_ADMIN_CREATE' => 'Rule has not been saved. Please try again!',
    'BACKEND_RULES_FLASH_FAIL_ADMIN_DELETE' => 'Rule has not been deleted. Please try again!',
    'BACKEND_RULES_INDEX_SUBTITLE' => 'Rules list',
    'BACKEND_RULES_INDEX_TITLE' => 'Access Control',
    'BACKEND_RULES_NOT_FOUND' => 'Error 404 - page not found!',
    'ERROR_MSG_INVALID_CHILDREN' => 'Invalid children',
    'ERROR_MSG_INVALID_NAMESPACE' => 'Invalid namespace',
    'ERROR_MSG_INVALID_PERMISSIONS_CHILDREN' => 'Invalid permissions children',
    'ERROR_MSG_INVALID_ROLES_CHILDREN' => 'Invalid roles permissions',
    'ERROR_MSG_INVALID_RULE_NAME' => 'Invalid rule name',
    'BACKEND_PERMISSIONS_ATTR_CHILDREN' => 'Children permissions',
    'BACKEND_PERMISSIONS_ATTR_DATA' => 'Data',
    'BACKEND_PERMISSIONS_ATTR_DESCRIPTION' => 'Description',
    'BACKEND_PERMISSIONS_ATTR_NAME' => 'Name',
    'BACKEND_PERMISSIONS_CHILDREN_PROMPT' => 'Choose children',
    'BACKEND_PERMISSIONS_CREATE_SUBMIT' => 'Save',
    'BACKEND_PERMISSIONS_CREATE_SUBTITLE' => 'Permission creating',
    'BACKEND_PERMISSIONS_CREATE_TITLE' => 'Access Control',
    'BACKEND_PERMISSIONS_FLASH_FAIL_ADMIN_CREATE' => 'Permission has not been saved. Please try again!',
    'BACKEND_PERMISSIONS_FLASH_FAIL_ADMIN_DELETE' => 'Permission has not been deleted. Please try again!',
    'BACKEND_PERMISSIONS_FLASH_FAIL_ADMIN_UPDATE' => 'Permission has not been updated. Please try again!',
    'BACKEND_PERMISSIONS_INDEX_SUBTITLE' => 'Permissions list',
    'BACKEND_PERMISSIONS_INDEX_TITLE' => 'Access Control',
    'BACKEND_PERMISSIONS_NOT_FOUND' => 'Error 404 - page not found!',
    'BACKEND_PERMISSIONS_RULE_NAME_PROMPT' => 'Choose a rule',
    'BACKEND_PERMISSIONS_UPDATE_SUBMIT' => 'Update',
    'BACKEND_PERMISSIONS_UPDATE_SUBTITLE' => 'Permission updating',
    'BACKEND_PERMISSIONS_UPDATE_TITLE' => 'Access Control',
    'BACKEND_ROLES_ATTR_DATA' => 'Data',
    'BACKEND_ROLES_ATTR_DESCRIPTION' => 'Description',
    'BACKEND_ROLES_ATTR_NAME' => 'Name',
    'BACKEND_ROLES_ATTR_PERMISSIONS' => 'Children permissions',
    'BACKEND_ROLES_ATTR_ROLES' => 'Children roles',
];
