<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'BACKEND_PERMISSIONS_ATTR_RULE_NAME' => 'Nome da regra',
    'BACKEND_ROLES_ATTR_RULE_NAME' => 'Nome da função',
    'BACKEND_ROLES_CREATE_SUBMIT' => 'Salvar',
    'BACKEND_ROLES_CREATE_SUBTITLE' => 'Criando uma função',
    'BACKEND_ROLES_CREATE_TITLE' => 'Controle de acesso',
    'BACKEND_ROLES_FLASH_FAIL_ADMIN_CREATE' => 'Função não foi salva. Tente novamente!',
    'BACKEND_ROLES_FLASH_FAIL_ADMIN_DELETE' => 'Função não foi deletada. Tente novamente!',
    'BACKEND_ROLES_FLASH_FAIL_ADMIN_UPDATE' => 'Função não foi atualizada. Tente novamente!!',
    'BACKEND_ROLES_INDEX_SUBTITLE' => 'Lista de funções',
    'BACKEND_ROLES_INDEX_TITLE' => 'Controle de Acesso',
    'BACKEND_ROLES_NOT_FOUND' => 'Erro 404 - Página não encontrada!',
    'BACKEND_ROLES_PERMISSIONS_PROMPT' => 'Escolha a permissão filha',
    'BACKEND_ROLES_ROLES_PROMPT' => 'Escolha uma função filha',
    'BACKEND_ROLES_RULE_NAME_PROMPT' => 'Escolha uma função',
    'BACKEND_ROLES_UPDATE_SUBMIT' => 'Atualizar',
    'BACKEND_ROLES_UPDATE_SUBTITLE' => 'Atualizando função',
    'BACKEND_ROLES_UPDATE_TITLE' => 'Controle de Acesso',
    'BACKEND_RULES_ATTR_NAME' => 'Nome da regra',
    'BACKEND_RULES_ATTR_NAMESPACE' => 'Namespace',
    'BACKEND_RULES_CREATE_SUBMIT' => 'Salvar',
    'BACKEND_RULES_CREATE_SUBTITLE' => 'Criando regra',
    'BACKEND_RULES_CREATE_TITLE' => 'Controle de Acesso',
    'BACKEND_RULES_FLASH_FAIL_ADMIN_CREATE' => 'Regra não foi criada. Tente novamente!',
    'BACKEND_RULES_FLASH_FAIL_ADMIN_DELETE' => 'Regra não foi excluída. Tente novamente!',
    'BACKEND_RULES_INDEX_SUBTITLE' => 'Lista de Regras',
    'BACKEND_RULES_INDEX_TITLE' => 'Controle de Acesso',
    'BACKEND_RULES_NOT_FOUND' => 'Erro 404 - Página não encontrada!',
    'ERROR_MSG_INVALID_CHILDREN' => 'Filho inválido',
    'ERROR_MSG_INVALID_NAMESPACE' => 'Namespace inválido',
    'ERROR_MSG_INVALID_PERMISSIONS_CHILDREN' => 'Permissões filhas inválidas',
    'ERROR_MSG_INVALID_ROLES_CHILDREN' => 'Função filhas inválidos',
    'ERROR_MSG_INVALID_RULE_NAME' => 'Nome da regra é inválido',
    'BACKEND_PERMISSIONS_ATTR_CHILDREN' => 'Permissões filhas',
    'BACKEND_PERMISSIONS_ATTR_DATA' => 'Data',
    'BACKEND_PERMISSIONS_ATTR_DESCRIPTION' => 'Descrição',
    'BACKEND_PERMISSIONS_ATTR_NAME' => 'Nome',
    'BACKEND_PERMISSIONS_CHILDREN_PROMPT' => 'Permissões filhas',
    'BACKEND_PERMISSIONS_CREATE_SUBMIT' => 'Salvar',
    'BACKEND_PERMISSIONS_CREATE_SUBTITLE' => 'Criando permissões',
    'BACKEND_PERMISSIONS_CREATE_TITLE' => 'Controle de Acesso',
    'BACKEND_PERMISSIONS_FLASH_FAIL_ADMIN_CREATE' => 'A permissão não foi salva. Por favor tente novamente!',
    'BACKEND_PERMISSIONS_FLASH_FAIL_ADMIN_DELETE' => 'A permissão não foi excluída. Por favor tente novamente!',
    'BACKEND_PERMISSIONS_FLASH_FAIL_ADMIN_UPDATE' => 'A permissão não foi atualizada. Por favor tente novamente!',
    'BACKEND_PERMISSIONS_INDEX_SUBTITLE' => 'Lista de permissões',
    'BACKEND_PERMISSIONS_INDEX_TITLE' => 'Controle de Acesso',
    'BACKEND_PERMISSIONS_NOT_FOUND' => 'Erro 404 - Página não encontrada!',
    'BACKEND_PERMISSIONS_RULE_NAME_PROMPT' => 'Escolha uma regra',
    'BACKEND_PERMISSIONS_UPDATE_SUBMIT' => 'Atualizar',
    'BACKEND_PERMISSIONS_UPDATE_SUBTITLE' => 'Atualizando permissão',
    'BACKEND_PERMISSIONS_UPDATE_TITLE' => 'Controle de Acesso',
    'BACKEND_ROLES_ATTR_DATA' => 'Dados',
    'BACKEND_ROLES_ATTR_DESCRIPTION' => 'Descrição',
    'BACKEND_ROLES_ATTR_NAME' => 'Nome',
    'BACKEND_ROLES_ATTR_PERMISSIONS' => 'Permissões filhas',
    'BACKEND_ROLES_ATTR_ROLES' => 'Papéis filhos',
];
